import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/Home.module.css'
import {useState, useEffect, useRef} from 'react';

export default function Home() {

  const [isLoading, setLoading] = useState(false);
  const [error, setError] = useState();
  const [data, setData] = useState();
  const [text, setText] = useState();

  const [time, setTime] = useState();

  useEffect(() => {
    fetch('/api/writing', { method: 'POST', body:'{"action": "GETALL"}' } )
      .then((res) => res.json())
      .then((res) => setData(res))
      .catch(e => setError(e));
  }, []);

  const [timeout, sett] = useState();
  const start = () => {
    setTime(30*60);
    sett(setInterval(() => {setTime(prev => prev-1)}, 1000))
  }

  const evaluate = () => {
    if(timeout){
      setLoading(true);
      setTimeout(() => setLoading(false), 3000);
      clearInterval(timeout);
      sett(null);
      
    }
  }


  if (error) return <div>Failed to load</div>
  if (!data || isLoading) return (
    <div className="spinner-border" role="status">
    </div>
  )
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Masterprep</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className="container mt-5">
        <div className={"row " +( isLoading === true ? 'd-none' : '')} >
            <div className="main col-md-9">
                <div className="question">
                    <h3>
                        Some people believe that teenagers should be required to do unpaid community work in their free
                        time. This can benefit teenagers and the community as well. To what extent do you agree or
                        disagree?
                    </h3>
                </div>
                <hr/>
                <div className="answer mt-4 lead">
                    <textarea className={timeout === null ? 'd-none' : ''} onChange={e => setText(e.target.value)} style={{width: "100%", height: "500px", border:"none"}} placeholder="Enter your answer"/>
                    <p className={(timeout === null) ? '': 'd-none'}>{text || ''}</p>
                </div>
            </div>
            <div className="sidebar col-md-3 mb-4">
                <div className="actions">
                  <div className={'btn btn-lg btn-primary d-block mb-2 ' + (time ? 'disabled' : '')} onClick={() => start()}>Start</div>
                  <div className={'btn btn-lg btn-primary d-block mb-2 ' + (!time || timeout === null ? 'disabled' : '')} onClick={() => evaluate()}>Evaluate</div>
                </div>
                <div className="timer mb-4 d-flex align-items-cetner justify-content-center mt-4">
                    <h1>{time ? '00:'+Math.floor(time/60) + ':' + Math.floor(time%60) : '00:30:00'}</h1>
                </div>
                <div className='d-none'>
                  <div className="problems mb-4">
                      <div className="card my-2 bg-light-warning py-2 px-3 my-2">
                          <div className="d-flex align-content-center align-items-center">

                              <div className="icon me-3 border justify-content-center align-content-center align-items-center d-flex"
                                  style={{minWidth: '40px', height: '40px', borderRadius: '100%'}}>
                                  <span className="count"><b>7</b></span>
                              </div>

                              <div className="text">
                                  Linking words, meeting the goal of 7 or more
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="stats mb-4">
                      <div className="row">
                          <span className="col">
                              4 paragraphs
                          </span>
                          <span className="col">
                              265 words
                          </span>
                      </div>
                  </div>
                  <hr/>
                  <div className="band mb-4 align-items-center align-content-center justify-content-center d-flex">
                      <div className="align-text-center text-center">
                          <h1>6.0</h1>
                          <span>Overall Band Score</span>
                      </div>

                  </div>
                  <hr/>
                  <div className="result mb-4">
                      <div>
                          <h6 className="result_title">COHERENCE AND COHESION: 9.0</h6>
                      </div>
                      <div>
                          <h6 className="result_title">LEXICAL RESOURCE: 5.0</h6>
                        
                      </div>
                      <div>
                          <h6 className="result_title">TASK ACHIEVEMENT: 4.0</h6>
                        
                      </div>
                      <div>
                          <h6 className="result_title">GRAMMATICAL RANGE: 5.0</h6>
                        
                      </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
      </main>

       
    </div>
  )
}
